documentation:
- changed-files:
  - any-glob-to-any-file: ['doc/source/**/*']
maintenance:
- changed-files:
  - any-glob-to-any-file: ['.github/**/*', '.flake8', 'pyproject.toml', '.codespellrc']
dependencies:
- changed-files:
  - any-glob-to-any-file: ['requirements/*']
